# Generated by Django 5.0.2 on 2024-03-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_emotion',
            new_name='totalEmotion',
        ),
    ]
