# Generated by Django 5.0.2 on 2024-03-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_user_fname_remove_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='emotion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
