# Generated by Django 5.0.2 on 2024-04-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_cart_products_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
    ]
